backend/models/Apple.php
<?php

namespace backend\models;

use backend\models\exceptions\StatusException;

/**
 * This is the model class for table "apple".
 *
 * @property int $id
 * @property string $color
 * @property string $birth_date
 * @property string|null $date_of_fall
 * @property float $size
 * @property string $status
 */
class Apple extends \yii\db\ActiveRecord
{
    
    public const ON_TREE = 'apple on tree';
    public const FELL = 'the apple fell to the ground';
    public const SPOILED = 'the apple is spoiled';
    
    public const SPOILED_TIME = 18000;
    
    public function __construct($config = array())
    {
        $this->status = self::ON_TREE;
        parent::__construct($config);
    }
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'apple';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['color', 'birth_date', 'size', 'status'], 'required'],
            [['birth_date', 'date_of_fall'], 'safe'],
            [['size'], 'number'],
            [['color', 'status'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'color' => 'Color',
            'birth_date' => 'Birth Date',
            'date_of_fall' => 'Date Of Fall',
            'size' => 'Size',
            'status' => 'Status',
        ];
    }
    
    public function eat(int $percent)
    {
        if($this->isFell()) {
            $p = (double) $percent / 100;
            if($p >= $this->size) {
                $this->delete();
            } else {
                $this->size -= $p;
                $this->save();
            }
        } else {
            throw new StatusException('The apple is still on the tree or spoiled.');
        }
    }
    
    public function spoil()
    {
        if($this->isFell() && !$this->isSpoiled()) {
            $this->status = self::SPOILED;
            $this->save();
        } else {
            throw new StatusException('The apple is still on the tree.');
        }
    }
    
    public function getIntSize()
    {
        return $this->size * 100;
    }
    
    public function getStatus()
    {
        return $this->status;
    }
    
    public function fallToGround()
    {
        $this->status = self::FELL;
        $this->date_of_fall = time();
        return $this->save();
    }
    
    public function isSpoiled(): bool
    {
        return $this->status === self::SPOILED;
    }
    
    public function isOnTree(): bool
    {
        return $this->status === self::ON_TREE;
    }
    
    public function isFell(): bool
    {
        return $this->status === self::FELL;
    }
    
}

backend/controllers/AppleController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\queries\AppleQuery;
use backend\models\forms\AppleEatingForm;
use backend\controllers\behaviors\AppleSpoiledBehavior;
use backend\controllers\behaviors\AccessBehavior;
use backend\models\Apple;
use backend\helpers\ColorHelper;

class AppleController extends \yii\web\Controller
{
    
    public function behaviors(): array
    {
        return [
            AppleSpoiledBehavior::class,
            AccessBehavior::class,
        ];
    }
    
    public function actionIndex()
    {
        $appleForm = new AppleEatingForm();
        $apples = AppleQuery::getAll();
        return $this->render('index', [
            'apples' => $apples,
            'appleForm' => $appleForm,
        ]);
    }
    
    public function actionView(int $id)
    {
        $appleForm = new AppleEatingForm();
        $apple = AppleQuery::getAppleById($id);
        
        return $this->render('view', [
            'apple' => $apple,
            'appleForm' => $appleForm,
            'p' => $p
        ]);
    }
    
    public function actionDelete(int $id)
    {
        $apple = AppleQuery::getAppleById($id);
        $apple->delete();
        return $this->redirect(['apple/index']);
    }
    
    public function actionDeleteAll()
    {
        Apple::deleteAll();
        return $this->redirect(['apple/index']);
    }
    
    public function actionFall(int $id)
    {
        $apple = AppleQuery::getAppleById($id);
        if($apple->fallToGround()) {
            return $this->redirect(['apple/index']);
        }
    }
    
    public function actionEat(int $id)
    {
        $appleForm = new AppleEatingForm();
        if(Yii::$app->request->post()) {
            if($appleForm->load(Yii::$app->request->post()) && $appleForm->eat($id)) {
                return $this->redirect(['apple/index']);
            }
        }
    }
    
    public function actionGenerate()
    {
        $count = random_int(2, 8);
        
        for($i = 0; $i < $count; $i++) {
            $apple = new Apple([
                'color' => ColorHelper::generateRandomColor(),
                'status' => Apple::ON_TREE,
                'birth_date' => strtotime('yesterday') - random_int(0, 500000),
                'date_of_fall' => null,
                'size' => 1.00
            ]);
            $apple->save();
        }
        return $this->redirect(['apple/index']);
    }

}

backend/views/apple/index.php
<?php
/* @var $this yii\web\View */
/* @var $apples[] backend\models\Apple */

use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>
<div class="container">
<h1>Apples</h1>
    <a href="<?= Url::to(['apple/generate']); ?>" class="btn btn-success">Generate apples</a>
    <a href="<?= Url::to(['apple/delete-all']); ?>" class="btn btn-danger" style="margin-left: 30px">Delete all apples</a>

    <div class="row">
        <?php if($apples): ?>
            <?php foreach ($apples as $apple): ?>
                <div class="col-sm-4">
                    <h3><?= $apple->color; ?> apple</h3>
                    <p><?= $apple->getIntSize(); ?></p>
                    <p>status: <?= $apple->getStatus(); ?></p>
                    <a href="<?= Url::to(['apple/view', 'id' => $apple->id]); ?>">View</a>
                    <?php if(!$apple->isFell() && !$apple->isSpoiled()): ?>
                        <a href="<?= Url::to(['apple/fall', 'id' => $apple->id]); ?>">Fall</a>
                    <?php endif; ?>
                    <a href="<?= Url::to(['apple/delete', 'id' => $apple->id]); ?>">Delete</a>
                    <?php $form = ActiveForm::begin([
                        'action' => ['apple/eat', 'id' => $apple->id],
                        'method' => 'post'
                    ]); ?>
                        <?= $form->field($appleForm, 'percent')->input('number', ['min' => 0, 'max' => $apple->getIntSize()]); ?>
                        <?= Html::submitButton('eat', ['class' => 'btn btn-success']); ?>
                    <?php ActiveForm::end(); ?>
                </div>
            <?php endforeach; ?>
        <?php else: ?>
            <h2>Яблок нет</h2>
        <?php endif; ?>
    </div>    
</div>

backend/views/apple/view.php
<?php
/* @var $this yii\web\View */
/* @var $apple frontend\models\Apple */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
?>
<h1>Apples</h1>

<div class="container">
    <div class="row">
        <div class="col-12">
            <h3><?= $apple->color; ?> apple</h3>
            <p><?= $apple->getIntSize(); ?></p>
            <p>status: <?= $apple->getStatus(); ?></p>
            <a href="<?= Url::to(['apple/index']); ?>">All apples</a>
            <?php if(!$apple->isFell() && !$apple->isSpoiled()): ?>
                <a href="<?= Url::to(['apple/fall', 'id' => $apple->id]); ?>">Fall</a>
            <?php endif; ?>
            <?php
            $form = ActiveForm::begin([
                        'action' => ['apple/eat', 'id' => $apple->id],
                        'method' => 'post'
            ]);
            ?>
            <?= $form->field($appleForm, 'percent')->input('number', ['min' => 0, 'max' => $apple->getIntSize()]); ?>
<?= Html::submitButton('eat', ['class' => 'btn btn-success']); ?>
<?php ActiveForm::end(); ?>
        </div>
    </div>    
</div>